### ISSUE TITLE
Provide basic target mapping system for packaging rules (pkg_filegroup)

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#298]
Originally brought up in #36, each packaging rule currently has its own scheme for laying out package contents, each with its own advantages and disadvantages.

Practically speaking, these are all just variations on ensuring that bazel targets are consistently mapped into the output package.  There should be a unified interface for this.

This is primarily the subject of the files in `pkg/experimental`, which represent a first pass at implementing this feature.  We believe we have identified the various shortcomings of this scheme, and an new, more streamlined, one is currently in progress.

This is tracking various pull requests other issues related to this mapping system, namely:

- [x] Backend providers (`PackageFilesInfo`, etc.) #246
- [x] File mapper (`pkg_files`) #273 
- [x] Directory mapper (`pkg_mkdirs`) #273
- [x] Symbolic link support (`pkg_mklink`) #293 
- [x] Grouping support (`pkg_filegroup`) #293 
- [x] Generic attribute support #290

This will cover most cases.  Other issues that should to be addressed at some point include (we are encountering issues with this internally):

- [x] `strip_prefix` on TreeArtifacts (this is a problem we're encountering internally) #269

Other, perhaps useful things that aren't as urgent:

- ~Default attribute derivation from inputs #302~
