### ISSUE TITLE
Bugs/missing features in pkg_filegroup-using pkg_rpm

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#300]
I will soon be submitting draft PR that will provide a `pkg_filegroup`-supporting `pkg_rpm` rule, based on the one in pkg/experimental/rpm.bzl, first created in #129.  All issues related to it are then inherited, but not immediately fixed to allow for swifter review.

This issue tracks known issue with this rule, including:

- [x] TreeArtifact installation is broken if done in the "wrong" order (#292)
- [x] It uses the deprecated `outputs` parameter, like the existing spec-file based `pkg_rpm` rule (#283)
- [x] It does not use the `rpmbuild` toolchain (#299)
- [x] It does not support `SOURCE_DATE_EPOCH` (#178)
- [x] The test cases are linux-only (#255)

**Comment by nacl** [comment]
All known issues resolved; resolving this ticket (yay!).
